version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: user_service_zookeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    container_name: user_service_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgres_ticket_service:
    image: postgres:latest
    container_name: ticket_service_postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=ticket_service"
      - "POSTGRES_PASSWORD=ticket_service"
    ports:
      - "5432:5432"  # credentials (ticket_service:ticket_service)

